<a href="https://colab.research.google.com/github/soanna21/Data-analysis-using-the-Pandas-library/blob/main/Project_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

results_file_path = '/content/drive/MyDrive/Навчання/project/results.csv'
schema_file_path = '/content/drive/MyDrive/Навчання/project/schema.csv'

df = pd.read_csv(results_file_path, encoding='utf-8')
df_schema = pd.read_csv(schema_file_path, encoding='utf-8')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/tmp/ipykernel_10344/1330406231.py:7: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(results_file_path, encoding='utf-8')

In [ ]:
df_schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [ ]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [ ]:
df_schema.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

1

In [ ]:
total_respondents = df['ResponseId'].nunique()
print(f"Загальна кількість респондентів: {total_respondents}")

Загальна кількість респондентів: 49191

2

In [ ]:
questions = set(df_schema['qname'].unique()) & set(df.columns)

df_filtered_questions = df[list(questions)]
respondents_complete_answers = df_filtered_questions.dropna().shape[0]

print(f"Кількість респондентів, які відповіли на всі спільні питання: {respondents_complete_answers}")
print(f"Загальна кількість респондентів: {total_respondents}")

percentage_complete = (respondents_complete_answers / total_respondents) * 100
print(f"Відсоток повноти відповідей: {percentage_complete:.2f}%")

Кількість респондентів, які відповіли на всі спільні питання: 0
Загальна кількість респондентів: 49191
Відсоток повноти відповідей: 0.00%

3

In [ ]:
print(f'Міри центральної тенденції:')

mean_value = df['ConvertedCompYearly'].mean()
print(f'Середнє значення: {round(mean_value, 2)} $/рік')

median_value = df['ConvertedCompYearly'].median()
print(f'Медіана: {round(median_value, 2)} $/рік')

mode_value = df['ConvertedCompYearly'].mode()
print(f'Мода:{round(mode_value, 2)} $/рік')

Міри центральної тенденції:
Середнє значення: 101761.54 $/рік
Медіана: 75320.0 $/рік
Мода:0    69609.0
Name: ConvertedCompYearly, dtype: float64 $/рік

4

In [ ]:
remote_workers_count = df[df['Employment'] == 'Remote'].shape[0]
print(f"Кількість респондентів, які працюють віддалено (Remote): {remote_workers_count}")

Кількість респондентів, які працюють віддалено (Remote): 0

5

In [ ]:
df['work_with_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

python_users = df['work_with_python'].sum()

python_percentage = (python_users / total_respondents) * 100

print(f"Відсоток респондентів: {python_percentage:.2f}%")

Відсоток респондентів: 37.54%

6

In [ ]:
df['Learned_with_online_courses'] = df['LearnCode'].str.contains('Online Courses or Certification', case=False, na=False)

# print(df[['LearnCode', 'Learned_with_online_courses']].head())

online_course_learners = df['Learned_with_online_courses'].sum()

print(f"Кількість респондентів, які навчалися через онлайн-курси: {online_course_learners}")

Кількість респондентів, які навчалися через онлайн-курси: 10973

7

In [ ]:
python_users = df[df['work_with_python'] == True]

python_users_cleaned = python_users.dropna(subset=['ConvertedCompYearly'])

py_progers_by_country = python_users_cleaned.groupby('Country')['ConvertedCompYearly'].agg([
    ('Average Compensation (USD)', 'mean'),
    ('Median Compensation (USD)', 'median')
]).reset_index()

display(py_progers_by_country.head())

               Country  Average Compensation (USD)  Median Compensation (USD)
0          Afghanistan                22328.666667                     1000.0
1              Albania                47217.600000                    50000.0
2              Algeria                20187.285714                     7088.0
3              Andorra               226103.500000                   226103.5
4  Antigua and Barbuda                    1.000000                        1.0

8

In [ ]:
highest_paid_specialists = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]

highest_paid_specialists = highest_paid_specialists.sort_values(by='ConvertedCompYearly', ascending=False)

highest_paid_specialists = highest_paid_specialists.reset_index(drop=True)

top_5_highest_paid = highest_paid_specialists.head(5)

display(top_5_highest_paid)

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0